### ISSUE TITLE
Composition of Dropdowns

### ISSUE THREAD

**Issue by faboweb** [fabric-design/components#104]
Chris found an interesting styling bug:

![image](https://user-images.githubusercontent.com/5869273/28619458-d3886cba-7208-11e7-92a1-3263f4d114ce.png)

As there is no margin defined for dropdown-labels, the labels are so tight to the former dropdown that the dropdown-menu-arrow points to the next label.
What should we do? Pull the arrow more to the input-field or create an input-field styling for the combination label/input?

**Comment by fragsalat** [comment]
Since this page is not styled properly you would have two simple solutions:
1. Make a margin bottom with $space-m on inputs
2. Make a margin top with $space-m on labels

**Comment by myueksel** [comment]
Ye I saw this yesterday and commented it as well...(at least I thought so) what ever... Yes Thomas is right. This example is not properly following our rules.

At first we're using Dropdown buttons instead of text fields.
![screen shot 2017-07-26 at 14 42 22](https://user-images.githubusercontent.com/25901307/28672322-be9f750a-72df-11e7-8c9d-fd11f8c29051.png)

Nonetheless, both elements following the same spacing rules. if you want use it like this anyways, you can use following spacings to ensure the correct visibility:
![screen shot 2017-07-26 at 14 07 16](https://user-images.githubusercontent.com/25901307/28672516-3d90b888-72e0-11e7-8cc2-1555e1359981.png)

Last not least... please try to bring the panel closer to its filter element:
![image 2](https://user-images.githubusercontent.com/25901307/28672571-6135b4c8-72e0-11e7-8434-20051a994122.png)

**Comment by fokusferit** [comment]
@myueksel @fragsalat do you think this one i still valid ? 

THe bug was related to a Prototype we developed but maybe we just close it and think again once we hit such issue again ?

**Comment by myueksel** [comment]
@fokusferit yes this was related to the prototype, so we can close this issue.
thanks!
