### ISSUE TITLE
"Select all" option in multi-dropdown

### ISSUE THREAD

**Issue by AdrianDampc** [fabric-design/components#135]

**Comment by AdrianDampc** [comment]
![select2](https://user-images.githubusercontent.com/26090170/32268212-5fbe0186-beee-11e7-8d9f-2f7dbe81ef8f.png)
![select1](https://user-images.githubusercontent.com/26090170/32268214-5fdf4030-beee-11e7-8d70-8686f844fc56.png)

**Comment by fragsalat** [comment]
This is can not work with multi select dropdowns because the selected items will appear on top of the dropdown. I would suggest do don't put every small feature in this already pretty complex component but find a different solution. A possibility could be a combination with a radio group and a dropdown.
Or a checkbox where I can select all items.

**Comment by fragsalat** [comment]
Like this
![dropdown-all](https://user-images.githubusercontent.com/1099747/32365774-8d03bddc-c07b-11e7-839e-65e945ac2684.png)
